/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gosjopavtixmzrhjgdmr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvc2pvcGF2dGl4bXpyaGpnZG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwNjMxNDEsImV4cCI6MjA3OTYzOTE0MX0.wdxJbT7HoVGQYeD5Rn-9sjdM__9u6DxKh-XYFk9r9sI"